version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - 22.x
    groups:
      eslint-family:
        patterns:
          - 'eslint'
          - '@typescript-eslint/*'
